name: Verify GCP Credentials

on:
  workflow_dispatch:  # Allows you to trigger this workflow manually

jobs:
  verify-gcp-creds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GCP Credentials
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" base64 --decode > base64 --decode > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
          gcloud config set project nebula-dev5

      - name: Install gcloud CLI
        run: |
          echo "Installing gcloud CLI..."
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli

      - name: Verify GCP Authentication
        run: |
          echo "Verifying GCP authentication..."
          gcloud auth list  # This will list the active account
          echo "Listing GCP projects..."
          gcloud projects list  # This will list GCP projects associated with the service account
