name: Verify GCP Credentials

on:
  workflow_dispatch:  # Allows you to trigger this workflow manually

jobs:
  verify-gcp-creds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Write the JSON secret to a file
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" | jq -r . > nebula-dev5.json
        
      - name: Display the file content (for debugging purposes)
        run: cat nebula-dev5.json

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: 'nebula-dev5'  # Replace with your GCP project ID

      - name: Verify GCP Authentication
        run: |
          echo "Verifying GCP authentication..."
          gcloud auth list  # This will list the active account
          echo "Listing GCP projects..."
          gcloud projects list  # This will list GCP projects associated with the service account
