name: Verify GCP Credentials

on:
  workflow_dispatch:  # Allows you to trigger this workflow manually

jobs:
  verify-gcp-creds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write the JSON secret to a file
        run: echo "${{ secrets.GCP_CREDENTIALS_JSON }}" > gcp-credentials.json

      - name: Display the file content (for debugging purposes)
        run: cat gcp-credentials.json

      - name: Authenticate with Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=gcp-credentials.json
          gcloud config set project nebula-dev5  # Replace with your GCP project ID

      - name: Verify GCP Authentication
        run: |
          echo "Verifying GCP authentication..."
          gcloud auth list  # This will list the active account
          echo "Listing GCP projects..."
          gcloud projects list  # This will list GCP projects associated with the service account
